name: test simple
run-name: test simple only

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  checkout-build-scan-simple:
    runs-on: ubuntu-latest

    permissions:
      statuses: write
      pull-requests: write

    steps:
      # -------------------------------------
      # we will have to checkout data before we can do anything
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

      # -------------------------------------
      # build someting, replace this with your build process
      # produces one filename as output in scanfile=<relative file path>
      - name: Build
        id: build

        shell: bash

        run: |
          # prepare the build process
          python3 -m pip install --upgrade pip
          pip install hatchling
          python3 -m pip install --upgrade build
          # make the actual build
          python3 -m build
          # produce a single artifact to scan and set the scanfile output variable
          echo "scanfile=$( ls dist/*.whl )" >> $GITHUB_OUTPUT

      # -------------------------------------
      - name: ReversingLabs apply rl-scanner to the build artifact
        id: rl-scan

        env:
          RLSECURE_ENCODED_LICENSE: ${{ secrets.RLSECURE_ENCODED_LICENSE }}
          RLSECURE_SITE_KEY: ${{ secrets.RLSECURE_SITE_KEY }}

        # uses: reversinglabs/gh-action-rl-scanner-simple@b0e7689b54df80bbb8a4af16b5f6c3dfc527240e # v1.0.0
        uses: maarten-boot/gh-action-rl-scanner-simple@v1.0.6
        with:
          artifact-to-scan: ${{ steps.build.outputs.scanfile }}
          report-path: "My_Report_Dir"

      - name: verbose show report
        if: success() || failure()
        shell: bash
        run: |
          ls -la
          ls -l 'My_Report_Dir'
